source('./source/libs.R')
source('./source/themes.R')
source('./source/palettes.R')

####################################################

#' Subset precipitation data sets
#' The function \code{subset_data} imports and crop the requested data sets through a shape file boundries.
#' @param name character string with the name of the desired data set.
#' @importFrom sf st_bbox
#' @importFrom rgdal readOGR
#' @importFrom sp over 
#' @importFrom viridis scale_fill_viridis
#' @import data.table, sf, sp, rgdal, lubridate, raster, ggplot 
#' @param data_list a list generated by \code{crop_data}
#' @param start_year numeric.
#' @param end_year numeric.
#' @param name_shp character string with the name of the desired shape file.
#' @return a list with the subsetted data sets
#' @export

# subset_function for CZ_pilot study --------------------------------------

crop_sel_data <- function(folder_path, name, start_year, end_year, shapefile_path, name_shp){
  if (name == "all") name <- c("cmap", "gpcc", "gpcp", "precl")
  memory.limit(size = 90000)
  folder_pat <- paste0(folder_path, "/", name, ".Rds") %>% as.list()
  dat_list <- lapply(folder_pat, readRDS)
  
  shapefile_path <- paste0(shapefile_path, "/", name_shp, ".shp")
  name_shp <- readOGR(shapefile_path)
  bound <- st_bbox(name_shp)
  
  subset_list <- lapply(dat_list, function(i) setDT(i)
                        [between(x, ((bound[1])-1), ((bound[3])+1)) & 
                            between(y, ((bound[2])-1), ((bound[4])+1))]
                        [year(Z) >= start_year & year(Z) <= end_year])
  
  precipe <- lapply(subset_list, function(i) {
    sp::coordinates(i) <- ~ x + y 
    proj4string(i) <- proj4string(name_shp)
    i
  })
  
  subse_preci <-  lapply(precipe, function(i) i[!is.na(over(i, as(name_shp, "SpatialPolygons"))), ])   
  
  subse_preci_datble <- lapply(subse_preci, as.data.table)
  
  saveRDS(subse_preci_datble, paste0(folder_path, "/", "subse_preci_list.Rds"))
  #data_preparation for plots
  subse_preci_datble <- rbindlist(subse_preci_datble)
  saveRDS(subse_preci_datble, paste0(folder_path, "/", "subse_preci.Rds"))
  
  mean_all <- subse_preci_datble[, .(value = mean(value), name = factor("average")), by = c("x", "y", "Z")]
  subse_preci_datble <- rbindlist(list(subse_preci_datble, mean_all))
  
  
  subse_preci_datble <- split(subse_preci_datble, subse_preci_datble$name)
  
 
  subse_preci_datble2 <- lapply(subse_preci_datble, function(i) setDT(i)
                                [, ':='(mon = month(Z), year = year(Z))]
                                [, year_val := sum(value), by = .(year, x, y)]
                                [, ':='(anl_mean = mean(year_val), anl_std = sd(year_val)),  by = .(x, y)]
                                [, reg_val := mean(value), by = .(mon, year)]
                                [, ':='(reg_monmean = mean(reg_val), reg_monstd = sd(reg_val)), by = mon])
  
  
  saveRDS(subse_preci_datble2, paste0(folder_path, "/", "combi_precip_list.Rds"))
  
  combi_precip <- rbindlist(subse_preci_datble2)
  saveRDS(combi_precip, paste0(folder_path, "/", "combi_precip.Rds"))
  
  #sptial_plots----------
  ggplot() +
    geom_raster(data = combi_precip[!(name == "average")], aes(x, y, fill = anl_mean)) + 
    coord_fixed(ratio = 1) + 
    scale_fill_viridis(direction = -1) + 
    labs(x = "Longitude", y = "Latitude") + 
    facet_wrap(~name, ncol = 2) + 
    ggtitle("Annual mean precipitation (mm/yr)") + 
    theme_small + 
    theme(plot.title = element_text(hjust = 0.5)) + 
    geom_path(data = name_shp, 
              aes(x = long, y = lat, group = group))
  ggsave(paste0(folder_path, "/Ann_mean_comb.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  ggplot() +
    geom_raster(data = combi_precip[!(name == "average")], aes(x, y, fill = anl_std)) + 
    coord_fixed(ratio = 1) + 
    scale_fill_viridis(direction = -1) + 
    labs(x = "Longitude", y = "Latitude") + 
    facet_wrap(~name, ncol = 2) + 
    ggtitle("Annual standad deviation (mm/yr)") + 
    theme_small + 
    theme(plot.title = element_text(hjust = 0.5)) + 
    geom_path(data = name_shp, 
              aes(x = long, y = lat, group = group))
  ggsave(paste0(folder_path, "/Ann_std_comb.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  #temporal_plots------
  ggplot(combi_precip, aes(Z, reg_val, color = name, linetype = name)) + 
    geom_line() + 
    geom_point() + 
    scale_linetype_manual(values = c(rep("dashed", 4), "solid")) + 
    labs(x = "Month", y = "Precipitation (mm)") + 
    theme_generic
  ggsave(paste0(folder_path, "/Monthly_line_comb.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  
  ggplot(combi_precip[!(name == "average")], aes(factor(mon), reg_val, fill = name)) + 
    geom_boxplot() + 
    labs(x = "Month", y = "Precipitation (mm)") + 
    theme_generic
  ggsave(paste0(folder_path, "/Boxplot_comb.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  
  ggplot(combi_precip[!(name == "average")], aes(factor(mon), reg_monmean, fill = name)) + 
    geom_bar(stat="identity", position=position_dodge(), alpha=0.5) + 
    geom_errorbar(aes(ymin = reg_monmean - reg_monstd, 
                      ymax = reg_monmean + reg_monstd), width = .4, 
                  position=position_dodge(width=0.90)) + 
    labs(x = "Month", y = "Precipitation (mm/month)") + 
    theme_generic
  ggsave(paste0(folder_path, "/Monthly_bar_comb.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  
}

#######################################################################################


# test subset_function for CZ_pilot study --------------------------------------

database <- "C:/Users/rkpra/OneDrive/Documents/R_projects/pRecipe/data/database"
shp_path <- "C:/Users/rkpra/OneDrive/Documents/R_projects/pRecipe/data/shapefiles"

ind_shp <- "C:/Users/rkpra/OneDrive/Documents/R_projects/pRecipe/data/shapefiles/India_state.shp"


India <- readOGR(ind_shp)

crop_sel_data(database, "all", 2001, 2012, shp_path, "SPH_KRAJ")
crop_sel_data(database, "all", 2001, 2012, shp_path, "India_state")

#Error: cannot allocate vector of size 548.9 Mb


###########################################################################

# Chhose_data and create a list of datatable ------------------------------

data_choose <- function(folder_path, ...) {
  names <- list(...)
  unlist(names)
  # return(names)
  if(names == "all") {
    names <- c("gpcp", "ghcn")
    names <- names <- strsplit(names, ",")
  } else {
    names <- list(...)
  }
  
  folder_pat <- paste0(folder_path, "/", names, ".Rds")
  dat_list <- lapply(folder_pat, readRDS) 
  
}


# subset_data(time, my_shapefile) ------------------------------------

data_subset <- function(folder_path, start_yaer, end_year, shapefile){
  
  
  
  shapefile_path <- paste0(shapefile_path, "/", name_shp, ".shp")
  name_shp <- readOGR(shapefile_path)
  bound <- st_bbox(name_shp)
  
  subset_list <- lapply(dat_list, function(i) setDT(i)
                        [between(x, ((bound[1])-1), ((bound[3])+1)) & 
                            between(y, ((bound[2])-1), ((bound[4])+1))]
                        [year(Z) >= start_year & year(Z) <= end_year])
  
  precipe <- lapply(subset_list, function(i) {
    sp::coordinates(i) <- ~ x + y 
    proj4string(i) <- proj4string(name_shp)
    i
  })
  
  subse_preci <-  lapply(precipe, function(i) i[!is.na(over(i, as(name_shp, "SpatialPolygons"))), ])   
  
  subse_preci_datble <- lapply(subse_preci, as.data.table)
  
  subse_preci_datble <- rbindlist(subse_preci_datble)
  
  saveRDS(subse_preci_datble, paste0(folder_path, "/", "subse_preci_datble1.Rds"))
  
  
}















