source('./source/libs.R')
source('./source/themes.R')
source('./source/palettes.R')

####################################################

#' Subset precipitation data sets
#' The function \code{subset_data} imports and crop the requested data sets through a shape file boundries.
#' @param name character string with the name of the desired data set.
#' @importFrom sf st_bbox
#' @importFrom rgdal readOGR
#' @importFrom sp over 
#' @importFrom viridis scale_fill_viridis
#' @import data.table, sf, sp, rgdal, lubridate, raster, ggplot 
#' @param data_list a list generated by \code{crop_data}
#' @param start_year numeric.
#' @param end_year numeric.
#' @param name_shp character string with the name of the desired shape file.
#' @return a list with the subsetted data sets
#' @export

crop_data <- function(folder_path, name, start_year, end_year, shapefile_path, name_shp){
  if (!is.character(folder_path)) stop ("folder_path should be a character string.")
  folder_path <- paste0(folder_path, "/", name, ".Rds")
  name <- readRDS(folder_path)
  shapefile_path <- paste0(shapefile_path, "/", name_shp, ".shp")
  name_shp <- readOGR(shapefile_path)
  bound <- st_bbox(name_shp)
  name_sub <- name[between(x, ((bound[1])-1), ((bound[3])+1)) & between(y, ((bound[2])-1), ((bound[4])+1))]
  name_sub <- name_sub[year(Z) >= start_year & year(Z) <= end_year]
  coordinates(name_sub) <- ~ x + y
  proj4string(name_sub) <- proj4string(name_shp)
  name_sub <- name_sub[!is.na(over(name_sub, as(name_shp, "SpatialPolygons"))), ]
  name_sub <- as.data.table(name_sub)
  saveRDS(name_sub, paste0(folder_path, "/../../database/subset.Rds"))
  
  #spatial_plots_mean_sd
  name_sub <- name_sub[, ':='(mon = month(Z), year = year(Z))]
  name_sub <- name_sub[, year_val := sum(value), by = .(year, x, y)]#annual sum for each grid and year
  name_sub <- name_sub[, ':='(anl_mean = mean(year_val), anl_std = sd(year_val)),  by = .(x, y)] #annual mean precipitation and sd for each grid
  shp <- fortify(name_shp)
  ggplot() +
    geom_raster(data = name_sub, aes(x, y, fill = anl_mean)) + 
    coord_fixed(ratio = 1) +
    scale_fill_viridis(direction = -1) + 
    labs(x = "Longitude", y = "Latitude") + 
    ggtitle("Annual mean precipitation (mm/yr)") + 
    theme_small + 
    geom_path(data = shp, 
              aes(x = long, y = lat, group = group))
  
  ggsave(paste0(folder_path, "/../../database/Ann_mean_plot.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  ggplot() +
    geom_raster(data = name_sub, aes(x, y, fill = anl_std)) + 
    coord_fixed(ratio = 1) +
    scale_fill_viridis(direction = -1) + 
    labs(x = "Longitude", y = "Latitude") + 
    theme_small + 
    geom_path(data = shp, 
              aes(x = long, y = lat, group = group))
  
  ggsave(paste0(folder_path, "/../../database/Stnd_dev.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  #temporal_plots(regional average)
  name_sub <- name_sub[, reg_meanmon := mean(value), by = .(mon, year)] #mean of all grids for each month & year wise
  saveRDS(name_sub, paste0(folder_path, "/../../database/subset_plot.Rds"))
  
  ggplot(name_sub, aes(Z, reg_meanmon)) + 
    geom_line() + 
    geom_point() + 
    labs(x = "Month", y = "Precipitation (mm)") + 
    theme_generic
  ggsave(paste0(folder_path, "/../../database/Monthly_line_plot.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  name_sub$mon <- factor(name_sub$mon)
  
  box_plot <- ggplot(name_sub, aes(mon, reg_meanmon)) + 
    geom_boxplot() + 
    labs(x = "Month", y = "Precipitation (mm)") + 
    theme_generic
  ggsave(paste0(folder_path, "/../../database/box_plot.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  ggplot(name_sub, aes(month(Z), reg_meanmon)) + 
    geom_line() + 
    geom_point() + 
    facet_wrap(~year, scales = 'free') + 
    scale_x_discrete(limits = factor(c(1:12))) + 
    theme_bw()
  ggsave(paste0(folder_path, "/../../database/facet_plot.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)

}

###############################################################################

# test --------------------------------------------------------------------
database <- "C:/Users/rkpra/OneDrive/Documents/R_projects/pRecipe/data/database/"
shp_path <- "C:/Users/rkpra/OneDrive/Documents/R_projects/pRecipe/data/shapefiles/"

crop_data(database, "cmap", 2001, 2010, shp_path, "SPH_KRAJ")

crop_data(database, "gpm_imergm", 2001, 2010, shp_path, "India_state")

####################################################################################

# subset_function for CZ_pilot study --------------------------------------

crop_sel_data <- function(folder_path, name, start_year, end_year, shapefile_path, name_shp){
  if (name == "all") name <- c("cmap", "gpcc", "gpcp", "precl")
  folder_pat <- paste0(folder_path, "/", name, ".Rds") %>% as.list()
  dat_list <- lapply(folder_pat, readRDS)
  
  shapefile_path <- paste0(shapefile_path, "/", name_shp, ".shp")
  name_shp <- readOGR(shapefile_path)
  bound <- st_bbox(name_shp)
  
  subset_list <- lapply(dat_list, function(i) setDT(i)
                 [between(x, ((bound[1])-1), ((bound[3])+1)) & 
                     between(y, ((bound[2])-1), ((bound[4])+1))]
                 [year(Z) >= start_year & year(Z) <= end_year])
  
  precipe <- lapply(subset_list, function(i) {
    sp::coordinates(i) <- ~ x + y 
    proj4string(i) <- proj4string(name_shp)
    i
  })
  
  subse_preci <-  lapply(precipe, function(i) i[!is.na(over(i, as(name_shp, "SpatialPolygons"))), ])   
  
  subse_preci_datble <- lapply(subse_preci, as.data.table)
  
  #data_preparation for plots
  
  subse_preci_datble2 <- lapply(subse_preci_datble, function(i) setDT(i)
                                [, ':='(mon = month(Z), year = year(Z))]
                                [, year_val := sum(value), by = .(year, x, y)]
                                [, ':='(anl_mean = mean(year_val), anl_std = sd(year_val)),  by = .(x, y)]
                                [, reg_meanmon := mean(value), by = .(mon, year)]
                                [, reg_meanmon_std := sd(value), by = .(mon, year)])
  
  combi_precip <- rbindlist(subse_preci_datble2)
  saveRDS(combi_precip, paste0(folder_path, "/", "combi_precip.Rds"))
  
  #sptial_plots----------
  ggplot() +
    geom_raster(data = combi_precip, aes(x, y, fill = anl_mean)) + 
    coord_fixed(ratio = 1) + 
    scale_fill_viridis(direction = -1) + 
    labs(x = "Longitude", y = "Latitude") + 
    facet_wrap(~name, ncol = 2) + 
    ggtitle("Annual mean precipitation (mm/yr)") + 
    theme_small + 
    theme(plot.title = element_text(hjust = 0.5)) + 
    geom_path(data = name_shp, 
              aes(x = long, y = lat, group = group))
  ggsave(paste0(folder_path, "/Ann_mean_comb.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  ggplot() +
    geom_raster(data = combi_precip, aes(x, y, fill = anl_std)) + 
    coord_fixed(ratio = 1) + 
    scale_fill_viridis(direction = -1) + 
    labs(x = "Longitude", y = "Latitude") + 
    facet_wrap(~name, ncol = 2) + 
    ggtitle("Annual standad deviation (mm/yr)") + 
    theme_small + 
    theme(plot.title = element_text(hjust = 0.5)) + 
    geom_path(data = name_shp, 
              aes(x = long, y = lat, group = group))
  ggsave(paste0(folder_path, "/Ann_std_comb.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  #temporal_plots------
  ggplot(combi_precip, aes(Z, reg_meanmon, color = name)) + 
    geom_line() + 
    geom_point() + 
    labs(x = "Month", y = "Precipitation (mm)") + 
    theme_generic
  ggsave(paste0(folder_path, "/Monthly_line_comb.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  
  ggplot(combi_precip, aes(factor(mon), reg_meanmon, fill = name)) + 
    geom_boxplot() + 
    labs(x = "Month", y = "Precipitation (mm)") + 
    theme_generic
  ggsave(paste0(folder_path, "/Boxplot_comb.png"), width = 7.2, height = 5.3, units = "in", dpi = 600)
  
  
}

#######################################################################################

# test subset_function for CZ_pilot study --------------------------------------

database <- "C:/Users/rkpra/OneDrive/Documents/R_projects/pRecipe/data/database"
shp_path <- "C:/Users/rkpra/OneDrive/Documents/R_projects/pRecipe/data/shapefiles"

ind_shp <- "C:/Users/rkpra/OneDrive/Documents/R_projects/pRecipe/data/shapefiles/India_state.shp"


India <- readOGR(ind_shp)

crop_sel_data(database, "all", 2001, 2010, shp_path, "SPH_KRAJ")
crop_sel_data(database, "all", 2001, 2010, shp_path, "India_state")

#Error: cannot allocate vector of size 548.9 Mb

memory.limit(size = 90000)
